### ISSUE TITLE
brs.log.lck

### ISSUE THREAD

**Issue by evol14life** [burst-apps-team/Qbundle#2]
I have downloaded and installed this wallet several times. and every time I close it out I get this error . I have rolled the block chain back and everything .. wiped the java cache .. its really starting to get frustrating ..any suggestions on how to fix it would be great..

**Comment by harryjph** [comment]
Which error? Could you post details?

**Comment by evol14life** [comment]
its a java lock file ..

**Comment by evol14life** [comment]
if it locks me out one more time I'm going to mine a different coin. I'm
tired of dealing with the issue that should already have been fixed

**Comment by evol14life** [comment]
brs.log.lck  this file shows up every time I try to open my wallet.

**Comment by evol14life** [comment]
[SEVERE] 2019-07-10 12:02:59 com.zaxxer.hikari.pool.HikariPool -
HikariPool-1 - Exception during pool initialization.
org.h2.jdbc.JdbcSQLException: General error:
"java.lang.NullPointerException" [50000-196]
 at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
 at org.h2.message.DbException.get(DbException.java:168)
 at org.h2.message.DbException.convert(DbException.java:295)
 at org.h2.engine.Database.openDatabase(Database.java:307)
 at org.h2.engine.Database.<init>(Database.java:270)
 at org.h2.engine.Engine.openSession(Engine.java:64)
 at org.h2.engine.Engine.openSession(Engine.java:176)
 at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
 at org.h2.engine.Engine.createSession(Engine.java:137)
 at org.h2.engine.Engine.createSession(Engine.java:27)
 at
org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
 at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
 at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
 at org.h2.Driver.connect(Driver.java:69)
 at
com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
 at
com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123)
 at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:365)
 at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:194)
 at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:460)
 at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:534)
 at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
 at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
 at brs.db.sql.Db.init(Db.java:102)
 at brs.Burst.loadWallet(Burst.java:171)
 at brs.Burst.init(Burst.java:150)
 at brs.Burst.main(Burst.java:135)
 at brs.BurstLauncher.main(BurstLauncher.java:51)
Caused by: java.lang.NullPointerException
 at org.h2.mvstore.db.ValueDataType.compare(ValueDataType.java:104)
 at org.h2.mvstore.MVMap.compare(MVMap.java:713)
 at org.h2.mvstore.Page.binarySearch(Page.java:334)
 at org.h2.mvstore.MVMap.binarySearch(MVMap.java:466)
 at org.h2.mvstore.MVMap.get(MVMap.java:455)
 at org.h2.mvstore.MVMap.remove(MVMap.java:543)
 at org.h2.mvstore.db.TransactionStore.rollbackTo(TransactionStore.java:506)
 at
org.h2.mvstore.db.TransactionStore$Transaction.rollback(TransactionStore.java:803)
 at
org.h2.mvstore.db.MVTableEngine$Store.initTransactions(MVTableEngine.java:256)
 at org.h2.engine.Database.open(Database.java:767)
 at org.h2.engine.Database.openDatabase(Database.java:276)
 ... 23 more
[SEVERE] 2019-07-10 12:02:59 brs.Burst -
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to
initialize pool: General error: "java.lang.NullPointerException" [50000-196]
java.lang.RuntimeException:
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to
initialize pool: General error: "java.lang.NullPointerException" [50000-196]
 at brs.db.sql.Db.init(Db.java:121)
 at brs.Burst.loadWallet(Burst.java:171)
 at brs.Burst.init(Burst.java:150)
 at brs.Burst.main(Burst.java:135)
 at brs.BurstLauncher.main(BurstLauncher.java:51)
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException:
Failed to initialize pool: General error: "java.lang.NullPointerException"
[50000-196]
 at
com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:569)
 at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:555)
 at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
 at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
 at brs.db.sql.Db.init(Db.java:102)
 ... 4 more
Caused by: org.h2.jdbc.JdbcSQLException: General error:
"java.lang.NullPointerException" [50000-196]
 at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
 at org.h2.message.DbException.get(DbException.java:168)
 at org.h2.message.DbException.convert(DbException.java:295)
 at org.h2.engine.Database.openDatabase(Database.java:307)
 at org.h2.engine.Database.<init>(Database.java:270)
 at org.h2.engine.Engine.openSession(Engine.java:64)
 at org.h2.engine.Engine.openSession(Engine.java:176)
 at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
 at org.h2.engine.Engine.createSession(Engine.java:137)
 at org.h2.engine.Engine.createSession(Engine.java:27)
 at
org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
 at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
 at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
 at org.h2.Driver.connect(Driver.java:69)
 at
com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
 at
com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123)
 at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:365)
 at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:194)
 at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:460)
 at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:534)
 ... 7 more
Caused by: java.lang.NullPointerException
 at org.h2.mvstore.db.ValueDataType.compare(ValueDataType.java:104)
 at org.h2.mvstore.MVMap.compare(MVMap.java:713)
 at org.h2.mvstore.Page.binarySearch(Page.java:334)
 at org.h2.mvstore.MVMap.binarySearch(MVMap.java:466)
 at org.h2.mvstore.MVMap.get(MVMap.java:455)
 at org.h2.mvstore.MVMap.remove(MVMap.java:543)
 at org.h2.mvstore.db.TransactionStore.rollbackTo(TransactionStore.java:506)
 at
org.h2.mvstore.db.TransactionStore$Transaction.rollback(TransactionStore.java:803)
 at
org.h2.mvstore.db.MVTableEngine$Store.initTransactions(MVTableEngine.java:256)
 at org.h2.engine.Database.open(Database.java:767)
 at org.h2.engine.Database.openDatabase(Database.java:276)
 ... 23 more

**Comment by harryjph** [comment]
Okay. I don't think the lock file has anything to do with this, it looks like you are having issues connecting to the database. I have not seen this before - have you tried portable mariadb?
